services:

  postgres:
    image: postgres:16-alpine
    container_name: coupon-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} "]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coupon-net

  coupon-service:
    image: discount-coupon-service:latest
    container_name: discount-coupon-service
    ports:
      - "8081:8080"
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true
      IPIFY_API_KEY: ${IPIFY_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - coupon-net
    restart: on-failure

volumes:
  db:

networks:
  coupon-net:
    driver: bridge